_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/usr1/home/tma1/Desktop/construction_detection/detectron_dev/models/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
SOLVER:
  BASE_LR: 0.001
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 8
  LR_SCHEDULER_NAME: WarmupMultiStepLR
TEST:
  EVAL_PERIOD: 250
DATASETS:
  META_PATH: ''
  CATEGORIES: (
    'unlabeled', 
    'ground',
    'rail track',
    'road',
    'sidewalk',
    'guard rail',
    'lane divider',
    'vegetation',
    'terrain',
  )
  TRAIN: ("nuscenes_train_detectron",)
  TEST: ("nuscenes_val_mini_detectron",)

